spring.datasource.url=${DB_TEST_URL:jdbc:mysql://localhost:3306/venta_sneackers_test}
spring.datasource.username=${DB_TEST_USER:root}
spring.datasource.password=${DB_TEST_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
eureka.client.enabled=false